version: '3'

services:
    api:
      build:
        context: .
      image: multi-tenance/api
      container_name: multi_tenance_api
      volumes:
        - ./src:/app/src
      ports:
        - "3000:3000"
    db_main:
      build:
        context: ./database
        target: main
      image: multi-tenance/db_main
      container_name: db_main
      volumes:
      - db_main:/var/lib/postgresql/data
      ports:
      - "5432:5432"
      restart:
        always
    db_tenant1:
      build:
        context: ./database
        target: tenant1
      image: multi-tenance/db_tenant1
      container_name: db_tenant1
      volumes:
      - db_tenant1:/var/lib/postgresql/data
      ports:
      - "5433:5432"
      restart:
        always

networks:
  default:
    external:
      name: dds
  development:
    external:
      name: development

volumes:
  db_main:
  db_tenant1:
